const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Mentor = require("./models/Mentor");

dotenv.config();

const mentors = [
  {
    name: "Dr. Rajesh Kumar",
    roleNumber: "R001",
    domain: "Software Engineering",
    careerGoal: "Full Stack Development",
    experience: "10+ years",
    mentoringStyle: "Hands-on, Project-based",
    email: "rajesh.kumar@example.com",
    linkedIn: "https://linkedin.com/in/rajeshkumar",
    phone: "+91-9876543210",
  },
  {
    name: "Dr. Priya Sharma",
    roleNumber: "R002",
    domain: "Data Science",
    careerGoal: "Data Scientist",
    experience: "8+ years",
    mentoringStyle: "Research-oriented, Academic",
    email: "priya.sharma@example.com",
    linkedIn: "https://linkedin.com/in/priyasharma",
    phone: "+91-9876543211",
  },
  {
    name: "Dr. Amit Patel",
    roleNumber: "R003",
    domain: "Machine Learning",
    careerGoal: "ML Engineer",
    experience: "12+ years",
    mentoringStyle: "Theoretical, Deep-dive",
    email: "amit.patel@example.com",
    linkedIn: "https://linkedin.com/in/amitpatel",
    phone: "+91-9876543212",
  },
  {
    name: "Dr. Sneha Reddy",
    roleNumber: "R004",
    domain: "Cybersecurity",
    careerGoal: "Security Analyst",
    experience: "9+ years",
    mentoringStyle: "Practical, Real-world scenarios",
    email: "sneha.reddy@example.com",
    linkedIn: "https://linkedin.com/in/snehareddy",
    phone: "+91-9876543213",
  },
  {
    name: "Dr. Vikram Singh",
    roleNumber: "R005",
    domain: "Cloud Computing",
    careerGoal: "Cloud Architect",
    experience: "11+ years",
    mentoringStyle: "Industry-focused, Case studies",
    email: "vikram.singh@example.com",
    linkedIn: "https://linkedin.com/in/vikramsingh",
    phone: "+91-9876543214",
  },
  {
    name: "Dr. Anjali Desai",
    roleNumber: "R006",
    domain: "Mobile Development",
    careerGoal: "Mobile App Developer",
    experience: "7+ years",
    mentoringStyle: "Collaborative, Workshop-based",
    email: "anjali.desai@example.com",
    linkedIn: "https://linkedin.com/in/anjalidesai",
    phone: "+91-9876543215",
  },
  {
    name: "Dr. Rahul Mehta",
    roleNumber: "R007",
    domain: "DevOps",
    careerGoal: "DevOps Engineer",
    experience: "10+ years",
    mentoringStyle: "Practical, Tool-focused",
    email: "rahul.mehta@example.com",
    linkedIn: "https://linkedin.com/in/rahulmehta",
    phone: "+91-9876543216",
  },
  {
    name: "Dr. Kavita Nair",
    roleNumber: "R008",
    domain: "Web Development",
    careerGoal: "Frontend Developer",
    experience: "8+ years",
    mentoringStyle: "Creative, Design-oriented",
    email: "kavita.nair@example.com",
    linkedIn: "https://linkedin.com/in/kavitanair",
    phone: "+91-9876543217",
  },
  {
    name: "Dr. Manoj Tiwari",
    roleNumber: "R009",
    domain: "Backend Development",
    careerGoal: "Backend Developer",
    experience: "9+ years",
    mentoringStyle: "System design, Architecture",
    email: "manoj.tiwari@example.com",
    linkedIn: "https://linkedin.com/in/manojtiwari",
    phone: "+91-9876543218",
  },
  {
    name: "Dr. Pooja Gupta",
    roleNumber: "R010",
    domain: "Artificial Intelligence",
    careerGoal: "AI Researcher",
    experience: "13+ years",
    mentoringStyle: "Research, Publications",
    email: "pooja.gupta@example.com",
    linkedIn: "https://linkedin.com/in/poojagupta",
    phone: "+91-9876543219",
  },
  {
    name: "Dr. Arjun Verma",
    roleNumber: "R011",
    domain: "Blockchain",
    careerGoal: "Blockchain Developer",
    experience: "6+ years",
    mentoringStyle: "Innovative, Emerging tech",
    email: "arjun.verma@example.com",
    linkedIn: "https://linkedin.com/in/arjunverma",
    phone: "+91-9876543220",
  },
  {
    name: "Dr. Neha Joshi",
    roleNumber: "R012",
    domain: "UI/UX Design",
    careerGoal: "UX Designer",
    experience: "8+ years",
    mentoringStyle: "User-centric, Design thinking",
    email: "neha.joshi@example.com",
    linkedIn: "https://linkedin.com/in/nehajoshi",
    phone: "+91-9876543221",
  },
  {
    name: "Dr. Ravi Malhotra",
    roleNumber: "R013",
    domain: "Game Development",
    careerGoal: "Game Developer",
    experience: "10+ years",
    mentoringStyle: "Creative, Portfolio-building",
    email: "ravi.malhotra@example.com",
    linkedIn: "https://linkedin.com/in/ravimalhotra",
    phone: "+91-9876543222",
  },
  {
    name: "Dr. Swati Iyer",
    roleNumber: "R014",
    domain: "Database Administration",
    careerGoal: "Database Admin",
    experience: "11+ years",
    mentoringStyle: "Performance, Optimization",
    email: "swati.iyer@example.com",
    linkedIn: "https://linkedin.com/in/swatiiyer",
    phone: "+91-9876543223",
  },
  {
    name: "Dr. Karan Shah",
    roleNumber: "R015",
    domain: "Software Engineering",
    careerGoal: "Tech Lead",
    experience: "12+ years",
    mentoringStyle: "Leadership, Team management",
    email: "karan.shah@example.com",
    linkedIn: "https://linkedin.com/in/karan Shah",
    phone: "+91-9876543224",
  },
  {
    name: "Dr. Meera Nair",
    roleNumber: "R016",
    domain: "Data Science",
    careerGoal: "Data Analyst",
    experience: "7+ years",
    mentoringStyle: "Analytical, Statistics-focused",
    email: "meera.nair@example.com",
    linkedIn: "https://linkedin.com/in/meeranair",
    phone: "+91-9876543225",
  },
  {
    name: "Dr. Suresh Menon",
    roleNumber: "R017",
    domain: "Machine Learning",
    careerGoal: "Deep Learning Engineer",
    experience: "9+ years",
    mentoringStyle: "Advanced topics, Research",
    email: "suresh.menon@example.com",
    linkedIn: "https://linkedin.com/in/sureshmenon",
    phone: "+91-9876543226",
  },
  {
    name: "Dr. Divya Kapoor",
    roleNumber: "R018",
    domain: "Cybersecurity",
    careerGoal: "Ethical Hacker",
    experience: "8+ years",
    mentoringStyle: "Security challenges, CTF",
    email: "divya.kapoor@example.com",
    linkedIn: "https://linkedin.com/in/divyakapoor",
    phone: "+91-9876543227",
  },
  {
    name: "Dr. Rohit Agarwal",
    roleNumber: "R019",
    domain: "Cloud Computing",
    careerGoal: "AWS Specialist",
    experience: "10+ years",
    mentoringStyle: "Certification, Best practices",
    email: "rohit.agarwal@example.com",
    linkedIn: "https://linkedin.com/in/rohitagarwal",
    phone: "+91-9876543228",
  },
  {
    name: "Dr. Ananya Rao",
    roleNumber: "R020",
    domain: "Mobile Development",
    careerGoal: "iOS Developer",
    experience: "7+ years",
    mentoringStyle: "Platform-specific, Native",
    email: "ananya.rao@example.com",
    linkedIn: "https://linkedin.com/in/ananyarao",
    phone: "+91-9876543229",
  },
  {
    name: "Dr. Varun Deshpande",
    roleNumber: "R021",
    domain: "DevOps",
    careerGoal: "Site Reliability Engineer",
    experience: "11+ years",
    mentoringStyle: "Reliability, Monitoring",
    email: "varun.deshpande@example.com",
    linkedIn: "https://linkedin.com/in/varundeshpande",
    phone: "+91-9876543230",
  },
  {
    name: "Dr. Ishita Banerjee",
    roleNumber: "R022",
    domain: "Web Development",
    careerGoal: "React Specialist",
    experience: "8+ years",
    mentoringStyle: "Framework-focused, Modern",
    email: "ishita.banerjee@example.com",
    linkedIn: "https://linkedin.com/in/ishitabanerjee",
    phone: "+91-9876543231",
  },
  {
    name: "Dr. Aditya Kulkarni",
    roleNumber: "R023",
    domain: "Backend Development",
    careerGoal: "Node.js Developer",
    experience: "9+ years",
    mentoringStyle: "API design, Microservices",
    email: "aditya.kulkarni@example.com",
    linkedIn: "https://linkedin.com/in/adityakulkarni",
    phone: "+91-9876543232",
  },
  {
    name: "Dr. Riya Chatterjee",
    roleNumber: "R024",
    domain: "Artificial Intelligence",
    careerGoal: "Computer Vision Engineer",
    experience: "10+ years",
    mentoringStyle: "Specialized AI, Image processing",
    email: "riya.chatterjee@example.com",
    linkedIn: "https://linkedin.com/in/riyachatterjee",
    phone: "+91-9876543233",
  },
  {
    name: "Dr. Nikhil Shetty",
    roleNumber: "R025",
    domain: "Blockchain",
    careerGoal: "Smart Contract Developer",
    experience: "7+ years",
    mentoringStyle: "Solidity, DeFi",
    email: "nikhil.shetty@example.com",
    linkedIn: "https://linkedin.com/in/nikhilshetty",
    phone: "+91-9876543234",
  },
  {
    name: "Dr. Tanvi Mehta",
    roleNumber: "R026",
    domain: "UI/UX Design",
    careerGoal: "Product Designer",
    experience: "9+ years",
    mentoringStyle: "Product thinking, Strategy",
    email: "tanvi.mehta@example.com",
    linkedIn: "https://linkedin.com/in/tanvimehta",
    phone: "+91-9876543235",
  },
  {
    name: "Dr. Abhishek Rao",
    roleNumber: "R027",
    domain: "Game Development",
    careerGoal: "Unity Developer",
    experience: "8+ years",
    mentoringStyle: "Game mechanics, Physics",
    email: "abhishek.rao@example.com",
    linkedIn: "https://linkedin.com/in/abhishekrao",
    phone: "+91-9876543236",
  },
  {
    name: "Dr. Pallavi Desai",
    roleNumber: "R028",
    domain: "Database Administration",
    careerGoal: "Data Engineer",
    experience: "10+ years",
    mentoringStyle: "Data pipelines, ETL",
    email: "pallavi.desai@example.com",
    linkedIn: "https://linkedin.com/in/pallavidesai",
    phone: "+91-9876543237",
  },
  {
    name: "Dr. Siddharth Nair",
    roleNumber: "R029",
    domain: "Software Engineering",
    careerGoal: "Engineering Manager",
    experience: "13+ years",
    mentoringStyle: "Career growth, Management",
    email: "siddharth.nair@example.com",
    linkedIn: "https://linkedin.com/in/siddharthnair",
    phone: "+91-9876543238",
  },
  {
    name: "Dr. Preeti Krishnan",
    roleNumber: "R030",
    domain: "Data Science",
    careerGoal: "Business Intelligence Analyst",
    experience: "8+ years",
    mentoringStyle: "Business insights, Visualization",
    email: "preeti.krishnan@example.com",
    linkedIn: "https://linkedin.com/in/preetikrishnan",
    phone: "+91-9876543239",
  },
];

async function seedMentors() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ Connected to MongoDB");

    // Clear existing mentors
    await Mentor.deleteMany({});
    console.log("✅ Cleared existing mentors");

    // Insert mentors
    await Mentor.insertMany(mentors);
    console.log(`✅ Seeded ${mentors.length} mentors successfully`);

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding mentors:", error);
    process.exit(1);
  }
}

seedMentors();

